require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  RubyInterpreters:
    - ruby

  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'

Performance:
  Exclude:
    - '**/test/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
