require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  RubyInterpreters:
    - ruby

  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Performance:
  Exclude:
    - '**/test/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
