version: '3.7'

services:
  rails:
    build:
      context: .
      dockerfile: docker/development.Dockerfile
      args:
        - RUBY_VERSION=2.7.1
        - BUNDLE_JOBS=15
        - BUNDLE_RETRY=2
        - NODE_VERSION=12
        - INSTALL_PG_CLIENT=false
    environment:
      - DATABASE_USER=postgres
      - DATABASE_HOST=postgres
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
      - gems:/gems
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: docker
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data

  solar:
    image: lawitschka/solargraph
    ports:
      - "7658:7658"
    volumes:
      - .:/home/groza/Workspace/rails_app_1
      - .:/app
      - gems:/gems
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache

volumes:
  gems:
  postgres:
  node_modules:
  packs:
  rails_cache: