on:
    push:
      branches:
        - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latestfile:///
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Build container image
      run: docker build -t registry.digitalocean.com/grozwaler/simple_app:$(echo $GITHUB_SHA | head -c7) .
